name: cs_monero_flutter_libs
description: "Binaries required to use cs_monero in a Flutter project"
version: 0.0.1
repository: https://github.com/cypherstack/cs_monero
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  cs_monero_flutter_libs_platform_interface:
    path: ../cs_monero_flutter_libs_platform_interface
  cs_monero_flutter_libs_android:
    path: ../cs_monero_flutter_libs_android
  cs_monero_flutter_libs_ios:
    path: ../cs_monero_flutter_libs_ios
  cs_monero_flutter_libs_linux:
    path: ../cs_monero_flutter_libs_linux
  cs_monero_flutter_libs_macos:
    path: ../cs_monero_flutter_libs_macos
  cs_monero_flutter_libs_windows:
    path: ../cs_monero_flutter_libs_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: cs_monero_flutter_libs_android
      ios:
        default_package: cs_monero_flutter_libs_ios
      linux:
        default_package: cs_monero_flutter_libs_linux
      macos:
        default_package: cs_monero_flutter_libs_macos
      windows:
        default_package: cs_monero_flutter_libs_windows
