include: package:lints/recommended.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "test/.test_coverage.dart"
    - "integrated_test/**"
    - "integration_test/**.dart"
    - "crypto_plugins/**"
    - "bin/cache/**"
    - "lib/generated_plugin_registrant.dart"

  # For more information see:
  # https://dart.dev/guides/language/analysis-options#enabling-additional-type-checks
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true


  errors:
    # Without ignore here, we cause import of all_lint_rules to warn, because some rules conflict.
    # We explicitly enabled even conflicting rules and are fixing the conflicts in this file.
    # Put it to warning temporarily, if you need troubleshoot lint rule settings.
    included_file_warning: ignore

    # Treat missing required parameters as an error, not as a hint or a warning.
    missing_required_param: error

    # Treat missing returns as an error, not as a hint or a warning.
    missing_return: error

    # Allow self-reference to deprecated members. This is done because otherwise we have
    # to annotate every member in every test, assert, etc., when we deprecate something.
    deprecated_member_use_from_same_package: ignore

    parameter_assignments: warning

    # Allow having TODOs in the code.
    todo: ignore

linter:
  rules:
    prefer_relative_imports: true
    avoid_relative_lib_imports: true
    no_leading_underscores_for_local_identifiers: false
    no_leading_underscores_for_library_prefixes: false
    avoid_print: true
    unawaited_futures: true
    avoid_double_and_int_checks: false
    constant_identifier_names: false
    prefer_final_locals: true
    prefer_final_in_for_each: true
    require_trailing_commas: true
  # avoid_print: false  # Uncomment to disable the `avoid_print` rule
  # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options