name: cs_monero
repository: https://github.com/cypherstack/cs_monero

packages:
  - "compat"
  - "cs_monero"
  - "cs_monero_flutter_libs"
  - "cs_monero_flutter_libs_android"
  - "cs_monero_flutter_libs_ios"
  - "cs_monero_flutter_libs_linux"
  - "cs_monero_flutter_libs_macos"
  - "cs_monero_flutter_libs_platform_interface"
  - "cs_monero_flutter_libs_platform_windows"
  - "cs_monero_flutter_libs_platform_windows"
  - "example_app"

command:
  version:
    # Only allow versioning to happen on main branch.
    branch: main
    # Generates a link to a prefilled GitHub release creation page.
    releaseUrl: true

  bootstrap:
    environment:
      sdk: ">=3.5.3 <4.0.0"
      flutter: ">=3.24.0"
    dependencies:
      ffi: ^2.1.0
      logger: ^2.4.0
      meta: ^1.15.0
      plugin_platform_interface: ^2.0.2

      cs_monero_flutter_libs_platform_interface:
        path: ../cs_monero_flutter_libs_platform_interface
      cs_monero_flutter_libs_android:
        path: ../cs_monero_flutter_libs_android
      cs_monero_flutter_libs_ios:
        path: ../cs_monero_flutter_libs_ios
      cs_monero_flutter_libs_linux:
        path: ../cs_monero_flutter_libs_linux
      cs_monero_flutter_libs_macos:
        path: ../cs_monero_flutter_libs_macos
      cs_monero_flutter_libs_windows:
        path: ../cs_monero_flutter_libs_windows

    dev_dependencies:
      lints: ^4.0.0
      test: ^1.24.0
      ffigen: ^14.0.0
      flutter_test:
        sdk: flutter
      flutter_lints: ^4.0.0
      mockito: ^5.4.4

scripts:
  analyze:
    run: melos exec -- flutter analyze
    description: Analyze all packages

  test:
    run: melos exec --dir-exists=test -c 1 -- flutter test
    description: Run tests for all packages

  coverage:
    steps:
      - melos exec --dir-exists=test -c 1 -- flutter test --coverage
      - melos exec --dir-exists=test -c 1 -- genhtml coverage/lcov.info --output-directory=coverage/
    description: Generate coverage for the selected package.