name: cs_monero_flutter_libs_windows
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://github.com/cypherstack/cs_monero

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  cs_monero_flutter_libs_platform_interface:
    path: ../cs_monero_flutter_libs_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: CsMoneroFlutterLibsWindowsPluginCApi
        dartPluginClass: CsMoneroFlutterLibsWindows
