name: compat
description: A compat layer for old flutter_libmonero.
version: 2.0.0
repository: https://github.com/cypherstack/cs_monero
publish_to: none

environment:
  sdk: ">=3.5.3 <4.0.0"

# Add regular dependencies here.
dependencies:
  hive_ce: ^2.13.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
