name: cs_monero
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/cypherstack/cs_monero
publish_to: none

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  ffi: ^2.0.1
  logger: ^2.4.0
  meta: ^1.15.0

# TODO: git and hash for monero.dart
#    # THIS HASH MUST MATCH `MONERO_C_HASH` in env.sh!!!!
#    monero:
#      git:
#        url: https://github.com/cypherstack/monero_c
#        ref: d04dcf67ec042fca76b48ffc09ea9d2ea4b5106e
#        path: impls/monero.dart
  monero:
    path: ../build/monero_c/impls/monero.dart

  compat:
    path: ../compat

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
