name: cs_monero
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/cypherstack/cs_monero
publish_to: none

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  ffi: ^2.0.1
  logger: ^2.4.0
  meta: ^1.15.0

# TODO: git and hash for monero.dart
  monero:
    path: ../build/monero_c/impls/monero.dart

  compat:
    path: ../compat

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
