name: cs_monero
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/cypherstack/cs_monero
publish_to: none

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.0
  logger: ^2.4.0
  meta: ^1.15.0

  # required for package:compat/old_cw_core/get_height_by_date.dart
  # This should be removed when possible
  compat:
    path: ../compat

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  ffigen: ^14.0.0
